name: Python Tests

on:
  push:
    branches:
      - main  # Configura para que se ejecute al hacer push a la rama 'main'
  pull_request:
    branches:
      - main  # También se ejecuta cuando se haga un pull request hacia 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Define que se ejecutará en una máquina virtual con Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Revisa tu repositorio para que esté disponible en el entorno

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Puedes usar la versión que prefieras (p.ej., '3.8', '3.9', etc.)

      - name: Run tests
        run: |
          python -m unittest discover -s .  # Ejecuta las pruebas en el repositorio
